In [ ]:
import numpy as np
x = np.array([range(i, i + 3) for i in [2, 4, 6]]) 
print(x)
print(x.ndim, x.shape, x.dtype)

In [16]:
x1 = np.array(range(10))
xr = x1.reshape((5, 2))
xr[1,1] = 20
xr[3,:] = [7, 7]  
xc = x1[::2].copy()
xc[1] = 100
print(x1)
print(xr)
print(xc)
print(id(x1), id(xr))
x1 is xr

[ 0  1  2 20  4  5  7  7  8  9]
[[ 0  1]
 [ 2 20]
 [ 4  5]
 [ 7  7]
 [ 8  9]]
[  0 100   4   7   8]
2291170593168 2291170594368


False

In [70]:
import timeit
nr = 1000000
values = np.random.randint(1, 10, size=nr)
y = np.zeros(2*nr)
print(timeit.timeit("np.power(2, values)", globals=globals(), number = 100))
print(timeit.timeit("2**values", globals=globals(), number = 100))
print(timeit.timeit("np.power(3, values, out = y[::2])", globals=globals(), number = 100))
print(timeit.timeit("y[::2] = 3**values", globals=globals(), number = 100))

1.1190480000000207
1.077491000000009
1.1197665999998208
1.2122437999996691


In [67]:
import numpy as np
import tracemalloc
np.random.seed(0)
nr = 1000000
values = np.random.randint(1, 10, size=nr)
y = np.zeros(2*nr)
tracemalloc.start()
np.power(2, values, out = y[::2])
first_size, first_peak = tracemalloc.get_traced_memory()
tracemalloc.clear_traces()
y[::2] = 2**values
second_size, second_peak = tracemalloc.get_traced_memory()
print(f"size: {first_size}, peak: {first_peak}")
print(f"size: {second_size}, peak: {second_peak}")
tracemalloc.stop()


size: 469, peak: 33955
size: 469, peak: 4000667


In [77]:
values = np.random.randint(1, 100, size=100000)
print(timeit.timeit("sum(values)", globals=globals(), number = 100))
print(timeit.timeit("np.add.reduce(values)", globals=globals(), number = 100))
print(timeit.timeit("np.sum(values)", globals=globals(), number = 100))

1.5982098999998016
0.004693999999744847
0.004966800000147487


In [78]:

x = np.array([1, 1, 1, 1, 1, 1])
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
print(x)


[1 1 2 2 2 1]


array([False, False,  True,  True,  True, False])