In [1]:
ana = 1
print(type(ana))
ana = "1"
print(type(ana))
ana = False
print(type(ana))

<class 'int'>
<class 'str'>
<class 'bool'>


In [6]:
gigi = [1,2,3]
coco = gigi
lala = coco

id(gigi) == id(coco) == id(lala)

True

In [10]:
gigi = [1, 2, 3]
last_id_gigi = id(gigi)
gigi[1] = 0
new_id_gigi = id(gigi)

assert(last_id_gigi == new_id_gigi)

costi = (1, 2, 3)
last_id_costi = id(costi)
costi[1] = 0
new_id_costi = id(costi)

# assert(last_id_costi == new_id_costi)

TypeError: 'tuple' object does not support item assignment

In [11]:
# ?

In [12]:
a = [1]
b = [3]
a = b


Liste

In [16]:
a = [1,2,3, "asdas"]


In [20]:
print(a)
a.append(1)
print(a)
a.pop(len(a)-1)
print(a)
a.pop(2)
print(a)

[1, 2, 'asdas']
[1, 2, 'asdas', 1]
[1, 2, 'asdas']
[1, 2]


In [56]:
import numpy as np

a = np.random.randint(10, size=(2,2,2))
print(a)
print('=====')
print(a.take(0, axis=0))
print('=====')
print(a.sum(axis=0))

[[[7 3]
  [5 4]]

 [[2 1]
  [2 1]]]
=====
[[7 3]
 [5 4]]
=====
[[9 4]
 [7 5]]


In [63]:
a = np.arange(1, 10)
b = a
print(a)
a[::2] += 1
print(a)
print(b)


[1 2 3 4 5 6 7 8 9]
[ 2  2  4  4  6  6  8  8 10]
[ 2  2  4  4  6  6  8  8 10]


In [89]:
a = list(np.arange(1, 10))
print(a[5])
a[2:4] = list(np.zeros(5, dtype=int))
print(a[5])

6
0


In [94]:
a = ['ana', 'gigi']
b = sorted(a, key=lambda x: x[1])
id(a) == id(b)

False

## dictionare

In [123]:
import random
a = {}
for i in range(0, 10000):
    a[np.random.rand(1)[0]] = (f"giig-{random.randint(0, 40)}", "costi")

# print(a)

In [124]:
b = {f'{v[0]}-{v[1]}':k for k,v in a.items()}
# print(b)

In [125]:
import timeit
from functools import partial

def find_in_a(a, str):
    for k, v in a.items():
        if str in v:
            return True
    return False

bounded = partial(find_in_a, a, 'giig-8-costi')

timeit.timeit(bounded, globals=globals(), number=10000)

3.664674499999819