In [8]:
# tabouri numpy
import numpy as np

a = np.random.normal(loc=5, scale=0.5, size=(2,2,2))
a

array([[[4.86765677, 5.45253812],
        [4.99726218, 3.73124173]],

       [[4.96283709, 4.54421781],
        [4.80213838, 5.07128979]]])

In [9]:
b = a[0, :, :]
b
b[0, 0] = 0
b

array([[0.        , 5.45253812],
       [4.99726218, 3.73124173]])

In [10]:
a

array([[[0.        , 5.45253812],
        [4.99726218, 3.73124173]],

       [[4.96283709, 4.54421781],
        [4.80213838, 5.07128979]]])

In [11]:
tab = np.random.random((6, 6))
tab = np.round(tab, 2)
print(tab)
print('=====')
print('=====')

for i in range(0, 4):
    print(tab[i:i+2, i:i+2])
    print('=====')
    print('=====')

[[0.95 0.17 0.55 0.09 0.37 0.44]
 [0.66 0.43 0.61 0.12 0.08 0.24]
 [0.14 0.87 0.11 0.61 0.35 0.  ]
 [0.89 0.12 0.12 0.61 0.9  0.01]
 [0.45 0.21 0.81 0.63 0.08 0.58]
 [0.36 0.76 0.12 0.99 0.44 0.11]]
=====
=====
[[0.95 0.17]
 [0.66 0.43]]
=====
=====
[[0.43 0.61]
 [0.87 0.11]]
=====
=====
[[0.11 0.61]
 [0.12 0.61]]
=====
=====
[[0.61 0.9 ]
 [0.63 0.08]]
=====
=====


In [12]:
slice1 = tab[0:2, :]
slice2 = tab[2:4, :]
slice3 = tab[4:, :]

slice2[:] = 0

print(tab)

[[0.95 0.17 0.55 0.09 0.37 0.44]
 [0.66 0.43 0.61 0.12 0.08 0.24]
 [0.   0.   0.   0.   0.   0.  ]
 [0.   0.   0.   0.   0.   0.  ]
 [0.45 0.21 0.81 0.63 0.08 0.58]
 [0.36 0.76 0.12 0.99 0.44 0.11]]


In [13]:
a = np.random.randint(0, 3, (3,3))
b = np.random.randint(0, 3, (6,6))

print(a)
print('===')
print(b)
print('===')
# print(a+b)

[[0 2 2]
 [1 1 1]
 [0 1 1]]
===
[[2 2 1 0 0 0]
 [0 2 2 0 1 1]
 [1 1 1 2 1 1]
 [1 0 1 2 1 2]
 [0 0 0 1 2 2]
 [0 1 2 1 1 2]]
===


In [14]:
# functii universale ufunc
import timeit
import tracemalloc

size = (10, 10)
values = np.random.random(size)
output = np.random.random(size)
times = 10000
def m1():
    for i in range(len(values)):
        output[i] = 1.0 / values[i]

tracemalloc.start()
print(timeit.timeit(m1, globals=globals(), number=10000))
print(tracemalloc.get_traced_memory())
tracemalloc.clear_traces()
print(timeit.timeit(lambda:1.0/values, globals=globals(), number=10000))
print(tracemalloc.get_traced_memory())
tracemalloc.clear_traces()
print(timeit.timeit(lambda:[1.0/x for x in np.nditer(values)], globals=globals(), number=10000))
print(tracemalloc.get_traced_memory())
tracemalloc.clear_traces()



0.33666590000001406
(1574, 24818)
0.023513400000013007
(1105, 25175)
2.5346091000000115
(1093, 25493)


In [15]:
a = np.random.normal(loc=5, scale=0.5, size=(2,2,2))
print(a)
print('===== axis 0')
print(a[0])
print(a[1])
print('===== min')
print(np.min(a, axis=0))
print('===== axis 1')
print(a[:, 0])
print(a[:, 1])
print('===== min')
print(np.min(a, axis=1))

[[[5.40830636 4.83859116]
  [4.86402389 4.86813898]]

 [[5.73600859 5.3965478 ]
  [4.65379221 5.38079042]]]
===== axis 0
[[5.40830636 4.83859116]
 [4.86402389 4.86813898]]
[[5.73600859 5.3965478 ]
 [4.65379221 5.38079042]]
===== min
[[5.40830636 4.83859116]
 [4.65379221 4.86813898]]
===== axis 1
[[5.40830636 4.83859116]
 [5.73600859 5.3965478 ]]
[[4.86402389 4.86813898]
 [4.65379221 5.38079042]]
===== min
[[4.86402389 4.83859116]
 [4.65379221 5.38079042]]


In [16]:
a.mean(axis=0)
a.std(axis=0)

array([[0.16385111, 0.27897832],
       [0.10511584, 0.25632572]])

In [47]:
# comparare, selectare
a = np.random.randint(0, 100, size=(100, 100))

print(np.any(a[a>1]))
print(a[(10 >= a) & (a > 5)])
i = np.random.randint(0, 90)
j = np.random.randint(0, 90)
b = a[i:i+10, j:j+10] 

i = np.random.randint(0, 90)
j = np.random.randint(0, 90)
c = a[i:i+10, j:j+10] 

np.all(b == c)

True
[10  7  8  6  6  7  8  6  8 10  9  6 10 10  9  8  8  6  9  9  9  7  6  6
  6  6 10 10  7  6  6  7  6  6 10  9  7  9  7  7 10  6  9  7  7  7 10  8
  6 10 10  6 10  7  7  6 10  8  6  9  8  6  8  8  8  7  9  9 10 10  9  9
  6  9  8  9  9  6  6  9  7  7 10 10 10 10  7  9  7  9  7 10  6 10  8 10
  7  9 10  6  8  8 10 10  9  7  7  6  7  9  7  7  7  7  8 10  8 10  9  7
  8  8  6  6  7 10  7  9  8 10  7 10  8  7  7  7  6  7  7 10  7  7  9  9
  9  7  8  7  8  8  8  6 10  8  6  7  8  7  8  6 10  6 10  8  6  9  9  9
  8  8  6  8  6  9  6  7  6  9 10  7 10  6 10  6  8  6  8  9  7 10  8 10
  9  8 10 10  9 10  7  8  9  8  9  8  6  9  9  7  8  9  6  6  9 10 10  6
  6 10 10 10  8  6  7  9 10 10  6  9  7 10  6 10  7  8 10  7  7  6  9  8
 10  7  7  6  9  9  8 10  8 10  9  7  8  6  6  6  6  7  7  9  8  7  7  7
  8  9  7  8  9  6  9 10  7  9  7  6  9 10  8  8  8  8  6  7  7  7  9  7
 10  7  9  6  9  7 10 10 10  7 10  6  8  8 10 10  9  9  8 10  7  8  7  7
  8 10  9  7  9 10  8 10  9  8 10  7  7  8  7 

False

In [61]:
a = np.random.randint(0, 100, size=(10, 10))
print(a)
print(np.sort(a, axis=0))
print(a.take(2, axis=1))

[[74 96 96 99 54 80 18  5 71 90]
 [54 62 92 55 31 26 52 56 63 90]
 [71 60  4 70 94 53 54 68  9 36]
 [ 0 47 37 82  7  2 65 70 97 33]
 [19 90 19 56 66 10 33 75 43 95]
 [15 20  2 87 57 93 55  8 10 69]
 [44 38 58 17 31 29 71 24 22 95]
 [62 37 11 96 59 85 62  0 17 46]
 [62 54 87 76 64 24 63 21 90 61]
 [43 96 50 15 36 14 47 48 83 32]]
[[ 0 20  2 15  7  2 18  0  9 32]
 [15 37  4 17 31 10 33  5 10 33]
 [19 38 11 55 31 14 47  8 17 36]
 [43 47 19 56 36 24 52 21 22 46]
 [44 54 37 70 54 26 54 24 43 61]
 [54 60 50 76 57 29 55 48 63 69]
 [62 62 58 82 59 53 62 56 71 90]
 [62 90 87 87 64 80 63 68 83 90]
 [71 96 92 96 66 85 65 70 90 95]
 [74 96 96 99 94 93 71 75 97 95]]
[96 92  4 37 19  2 58 11 87 50]


In [1]:
import numpy as np

# create a 2D array
arr = np.array([[3, 1, 4],
                [1, 5, 9],
                [2, 6, 5],
                [3, 5, 8]])

# get the indices that would sort the third column
indices = np.argsort(arr[:, 2])

# reorder the rows based on the sorted indices
sorted_arr = arr[indices]

print(sorted_arr)

[[3 1 4]
 [2 6 5]
 [3 5 8]
 [1 5 9]]
